language: node_js

node_js:
  - "6"

services: mongodb

git:
  submodules: false

before_script:
  - npm i -g gulp
  - gulp build
  - ./build/popcorn-api.js --server &

script:
  - npm test

after_script:
  - "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
