language: node_js

node_js:
  - '6'
  - '7'

addons:

  apt:

    sources:
      - mongodb-upstart
      - mongodb-3.2-precise

    packages:
      - mongodb-org-server
      - mongodb-org-shell

env:
  - NODE_ENV=test

git:
  submodules: false

before_script:
  - npm run lint
  - gulp build
  - npm run server-dev &

script:
  - dredd
after_script:

  - npm run coverage

before_install:
  - npm install -g eslint gulp dredd@stable
