sudo: required

dist: trusty

language: node_js

node_js:
  - '6'
  - '7'

env:
  - NODE_ENV=test

git:
  submodules: false

before_script:
  - sudo apt-get install mongodb -y
  - mongo --version
  - npm install -g eslint gulp dredd@stable babel-cli
  - npm run lint
  - gulp build
