sudo: required

dist: trusty

language: node_js

node_js:
  - 6
  - 7
  - 8

addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
      - mongodb-org-tools

services:
  - mongodb

env:
  - NODE_ENV=test

git:
  submodules: false

jobs:
  include:
    - stage: lint
      before_script: 
        - npm i -g flow-typed
        - flow-typed install
      script: npm run flow
      script: npm run lint
    - stage: test
      script: npm run test
      after_success: npm run coveralls
    - stage: build
      before_script: npm i -g gulp
      script: npm run gulp
    - stage: pages
      script: npm run docs
