language: node_js
node_js:
  - "6"
services: mongodb
git:
  submodules: false
before_script:
  - npm install -g gulp
script:
  - gulp
  - npm test
after_script:
  - "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
